services:
  # Servidor de PRODUCCIÓN (Backend)
  - type: web
    name: entrycipher-backend
    env: python
    plan: free
    branch: main
    healthCheckPath: /health
    buildCommand: "pip install --upgrade pip && pip install --only-binary :all: -r Backend/requirements.txt"
    startCommand: "cd Backend && uvicorn main:app --host 0.0.0.0 --port $PORT"

  # Servidor de DESARROLLO (Backend)
  - type: web
    name: entrycipher-backend-dev
    env: python
    plan: free
    branch: main
    healthCheckPath: /health
    buildCommand: "pip install --upgrade pip && pip install --only-binary :all: -r Backend/requirements.txt"
    startCommand: "cd Backend && uvicorn main:app --host 0.0.0.0 --port $PORT"

  # Frontend de PRODUCCIÓN
  - type: web
    name: entrycipher-frontend
    env: static
    plan: free
    branch: main
    publishPath: Frontend/dist/frontend/browser
    buildCommand: "cd Frontend && npm install && npm run build"

  # Frontend de DESARROLLO
  - type: web
    name: entrycipher-frontend-dev
    env: static
    plan: free
    branch: main
    publishPath: Frontend/dist/frontend/browser
    buildCommand: "cd Frontend && npm install && npm run build"
